default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['host_postgres'] %>
  port: <%= ENV['port_postgres'] %>
  username: <%= ENV['username_postgres'] %>
  password: <%= ENV['password_postgres'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: alerta_covid_development

test:
  <<: *default
  database: alerta_covid_test

production:
  <<: *default
  database: alerta_covid_production
  username: alerta_covid
  password: <%= ENV['ALERTA_COVID_DATABASE_PASSWORD'] %>